#!/bin/bash

red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
plain='\033[0m'

# 检查是否为 root 用户
if [[ $EUID -ne 0 ]]; then
    echo -e "${red}错误：${plain} 必须使用 root 用户运行此脚本！\n"
    exit 1
fi

# 检查操作系统类型
if cat /etc/*release | grep -q -E -i "debian"; then
    release="debian"
elif cat /etc/*release | grep -q -E -i "ubuntu"; then
    release="ubuntu"
elif cat /etc/*release | grep -q -E -i "centos|red hat|redhat"; then
    release="centos"
else
    echo -e "${red}错误：${plain} 该脚本不支持当前操作系统！\n"
    exit 1
fi

# 安装基本依赖
install_base() {
    if [[ ${release} == "centos" ]]; then
        yum install -y wget curl tar iproute2
    else
        apt update && apt install -y wget curl tar iproute2
    fi
}

# 设置源路由
setup_source_routing() {
    # 获取所有 IPv4 地址和对应的子网掩码、广播地址、网卡名
    mapfile -t ips < <(ip -o -4 addr show | awk '{print $4, $6}')

    # 为每个 IP 地址配置源路由
    counter=1
    for ip_info in "${ips[@]}"; do
        ip=$(echo $ip_info | awk '{print $1}' | cut -d'/' -f1)
        dev=$(echo $ip_info | awk '{print $2}')

        # 获取网关地址
        gw=$(ip route | grep default | awk '{print $3}')

        # 添加路由规则和路由
        ip rule add from $ip table $((100 + counter))
        ip route add default via $gw dev $dev table $((100 + counter))

        echo -e "${green}为 IP $ip 配置了源路由。${plain}"

        ((counter++))
    done
}

# 自动设置账户名、密码和端口
config_after_install() {
    echo -e "${yellow}自动设置账户名、密码和端口${plain}"
    config_account="admin"
    config_password="admin996"
    config_port=49999

    /usr/local/x-ui/x-ui setting -username ${config_account} -password ${config_password}
    /usr/local/x-ui/x-ui setting -port ${config_port}
    echo -e "${green}设置完成${plain}"
}

# 安装 X-UI
install_x-ui() {
    systemctl stop x-ui
    cd /usr/local/

    if [ -e /usr/local/x-ui/ ]; then
        rm /usr/local/x-ui/ -rf
    fi

    last_version=$(curl -Ls "https://api.github.com/repos/vaxilu/x-ui/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
    wget -N --no-check-certificate -O /usr/local/x-ui-linux.tar.gz https://github.com/vaxilu/x-ui/releases/download/${last_version}/x-ui-linux.tar.gz
    tar zxvf x-ui-linux.tar.gz
    rm x-ui-linux.tar.gz -f
    cd x-ui
    chmod +x x-ui bin/xray-linux-*
    cp -f x-ui.service /etc/systemd/system/
    systemctl daemon-reload
    systemctl enable x-ui
    systemctl start x-ui

    echo -e "${green}x-ui v${last_version}${plain} 安装完成，面板已启动"
    echo -e "用户名: ${config_account}, 密码: ${config_password}, 端口: ${config_port}"
    echo -e "请确保端口 ${config_port} 已在防火墙中开放"
}

# 开始安装
echo -e "${green}开始安装${plain}"
install_base
setup_source_routing
install_x-ui $1
config_after_install
